# Generated by Django 5.1.4 on 2024-12-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_user_options_remove_project_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
